server:
  port: 8081
  servlet:
    context-path: /sell

spring:
  datasource:
        url: jdbc:mysql://localhost:3306/sys?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database: mysql
      show-sql: true
      hibernate:
          ddl-auto: update
          naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
          enable_lazy_load_no_trans : true
  jackson:
    #属性为null，不返回字段
    default-property-inclusion: non_null
  redis:
      host: 127.0.0.1
      port: 6379
wechat:
  mpAppId: wxe7e587f28761cda2
  mpAppSecret: 4768af2cb542285081b1bb523afaf473
  #开发平台，扫描登录
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://hp5fef.natappfree.cc/sell/pay/notify
  templateId:
    orderStatus: jdd0p95dD39oImBFLh5PBvnMtHJk-tcp5SRz9tqKeeU
projecturl:
  wechatMpAuthorize: http://kpknew.natappfree.cc
  wechatOpenAuthorize: http://kpknew.natappfree.cc
  sell: http://127.0.0.1:8081